import {
  BarChart3,
  FileText,
  Gauge,
  Lightbulb,
  Share2,
  Sparkles
} from "lucide-react";

export const trustedTools = [
  "ChatGPT",
  "Claude",
  "Cursor",
  "Copilot",
  "Gemini",
  "OpenAI API"
];

export const features = [
  {
    title: "AI Spend Analysis",
    description:
      "Map recurring AI seats, usage tiers, and API commitments into a clean spend view your team can actually act on.",
    icon: BarChart3
  },
  {
    title: "Optimization Recommendations",
    description:
      "Surface duplicate licenses, underused plans, and consolidation paths without forcing a procurement rebuild.",
    icon: Lightbulb
  },
  {
    title: "Shareable Audit Reports",
    description:
      "Turn your audit into an investor, finance, or leadership-ready report with clear savings and next steps.",
    icon: Share2
  }
];

export const steps = [
  {
    title: "Add Your AI Stack",
    description: "Select the tools your team already uses and enter simple monthly spend ranges.",
    icon: Sparkles
  },
  {
    title: "Analyze Spending",
    description: "StackPilot organizes overlap, utilization, and pricing patterns into a readable model.",
    icon: Gauge
  },
  {
    title: "Reduce Waste",
    description: "Review specific cuts, plan changes, and workflow recommendations before you act.",
    icon: FileText
  }
];

export const testimonials = [
  {
    quote:
      "StackPilot gave us the vocabulary to talk about AI spend before it became another invisible SaaS line item.",
    name: "Maya Patel",
    role: "Founder, Northstar Labs"
  },
  {
    quote:
      "The mock report is exactly how I want tool recommendations presented: calm, specific, and finance-friendly.",
    name: "Daniel Reeves",
    role: "Engineering Manager, RelayOps"
  },
  {
    quote:
      "We needed a fast way to show leadership where AI budget was leaking. This feels purpose-built for that moment.",
    name: "Iris Chen",
    role: "CTO, AlloyFrame"
  }
];

export const faqs = [
  {
    question: "Is pricing data private?",
    answer:
      "Yes. This frontend phase stores nothing. Future audit flows should be designed so sensitive pricing inputs are handled deliberately and transparently."
  },
  {
    question: "Are recommendations generated by AI?",
    answer:
      "The current demo uses static examples. Later phases can add recommendation logic once product rules and data handling are defined."
  },
  {
    question: "Do you store our AI tool data?",
    answer:
      "Not in this phase. There is no backend, database, API route, or authentication layer in the current implementation."
  },
  {
    question: "Can teams use this together?",
    answer:
      "The interface is designed for team workflows, but collaboration, accounts, and permissions are reserved for a later build phase."
  },
  {
    question: "Which tools are compatible?",
    answer:
      "The visual model covers ChatGPT, Claude, Cursor, Copilot, Gemini, and OpenAI API today, with an architecture ready for more categories."
  }
];
